baseurl: "/webstie_v5/" # The name of your GitHub repository
url: "https://yourcustomdomain.com" # Your custom domain
title: "Allied Algorithms 58590"
description: "FLL Team 58590's website."
author: "AlliedAlgos"
email: "alliedalgorithms@gmail.com"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - README.md